/**
 * Hand-maintained row types matching SYSTEM-DESIGN-NEXTJS.md §16 and the
 * migrations in supabase/migrations/. Not generated by `supabase gen
 * types` - that needs a personal access token this environment doesn't
 * have yet. Worth wiring up later; until then, these are the one place
 * that knows each table's shape, per Task 5's own scope ("thin, focused
 * modules... they are the only place that knows the table shapes").
 */
import type { RunLimits, RunStatus, LeadQualificationStatus, ToolCallStatus, Runner, Scraper } from "../domain/types";
import type { RunValidationVerdict } from "../schemas/validation";

export interface RunRow {
  id: string;
  user_id: string;
  objective_raw: string;
  icp: Record<string, unknown> | null;
  status: RunStatus;
  runner: Runner | null;
  model: string | null;
  scraper: Scraper | null;
  replay_mode: boolean;
  fixture_set: string | null;
  limits: Partial<RunLimits>;
  counters: Record<string, number>;
  clarification_question: string | null;
  clarification_answer: string | null;
  clarification_count: number;
  validation_verdict: RunValidationVerdict | null;
  validation_reason: string | null;
  validation_confidence: number | null;
  validation_missing_criteria: string[] | null;
  validation_dismissed_at: string | null;
  failure_reason: string | null;
  partial_reason: string | null;
  worker_id: string | null;
  heartbeat_at: string | null;
  attempt: number;
  queued_at: string | null;
  started_at: string | null;
  finished_at: string | null;
  created_at: string;
  idempotency_key: string | null;
  /** Task 20's failure-injection toggle - see packages/core/src/providers/failure-injection.ts. */
  injected_failure: string | null;
}

export interface NewRun {
  user_id: string;
  objective_raw: string;
  icp?: Record<string, unknown> | null;
  status?: RunStatus;
  runner?: Runner;
  model?: string;
  scraper?: Scraper;
  replay_mode?: boolean;
  fixture_set?: string;
  limits?: Partial<RunLimits>;
  validation_verdict?: RunValidationVerdict;
  validation_reason?: string;
  validation_confidence?: number;
  validation_missing_criteria?: string[];
  validation_dismissed_at?: string;
  idempotency_key?: string;
  injected_failure?: string;
  queued_at?: string;
}

export interface LeadRow {
  id: string;
  run_id: string;
  company_name: string;
  company_domain: string;
  qualification_status: LeadQualificationStatus;
  confidence: number;
  fit_reasons: string[];
  concerns: string[];
  source_urls: string[];
  source_summary: string | null;
  discovery_payload: Record<string, unknown> | null;
  scraper_used: Scraper | null;
  injection_flagged: boolean;
  evidence_gap_reason: string | null;
  created_at: string;
  updated_at: string;
}

export type NewLead = Omit<LeadRow, "id" | "created_at" | "updated_at">;

export interface OutreachDraftRow {
  id: string;
  lead_id: string;
  channel: "email" | "linkedin";
  step: 1 | 2 | 3;
  subject: string | null;
  body: string;
  personalization_note: string;
  grounding_check: Record<string, unknown> | null;
  flagged_unsupported: boolean;
  created_at: string;
}

export type NewOutreachDraft = Omit<OutreachDraftRow, "id" | "created_at" | "flagged_unsupported"> & {
  flagged_unsupported?: boolean;
};

export interface ToolCallRow {
  id: string;
  run_id: string;
  seq: number;
  tool_name: string;
  purpose: string | null;
  input_summary: string | null;
  result_summary: string | null;
  status: ToolCallStatus;
  error_message: string | null;
  denial_reason: string | null;
  duration_ms: number | null;
  estimated_cost_usd: number | null;
  result_data: unknown | null;
  created_at: string;
}

export interface AgentEventRow {
  id: string;
  run_id: string;
  seq: number;
  type: "phase" | "assistant_text" | "tool_use" | "tool_result" | "skill_load" | "limit_hit" | "injection_flag" | "system";
  payload: Record<string, unknown> | null;
  created_at: string;
}

export interface CostLedgerRow {
  id: string;
  run_id: string;
  provider: "apify" | "firecrawl" | "anthropic" | "google";
  unit_type: string;
  units: number;
  estimated_cost_usd: number;
  model: string | null;
  ref: string | null;
  created_at: string;
}

export type NewCostLedgerEntry = Omit<CostLedgerRow, "id" | "created_at">;

export interface DiscoveryCacheRow {
  id: string;
  cache_key: string;
  actor_id: string | null;
  input_json: Record<string, unknown> | null;
  results: unknown;
  item_count: number | null;
  created_at: string;
  expires_at: string | null;
}

export interface ScrapeCacheRow {
  id: string;
  url_hash: string;
  url: string;
  scraper: Scraper;
  title: string | null;
  content_md: string | null;
  http_status: number | null;
  fetched_at: string;
  expires_at: string | null;
}

export interface RunQualityReportRow {
  run_id: string;
  checks: unknown;
  scorecard: unknown;
  passed: boolean;
  summary: string;
  created_at: string;
}

export interface RunSummary {
  status: RunStatus;
  limits: Partial<RunLimits>;
  counters: Record<string, number>;
  qualified_count: number;
  needs_review_count: number;
  not_qualified_count: number;
  tool_call_count: number;
}
